name: Quality
on: [push, pull_request]

jobs:
  tests:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Lint
        run: pnpm run lint

      - name: TypeScript
        run: pnpm run typecheck

      - name: Jest
        run: pnpm run test
